[package]
name = "advent-of-code-2020"
version = "0.1.0"
authors = ["Ferrix Hovi <ferrix@ferrix.fi"]

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
serde = "1.0.117"
serde_scan = "0.4.1"
serde_derive = "1.0.117"
